### ISSUE TITLE
Mockup

### ISSUE THREAD

**Issue by sophalS** [pnc-virtual-company/2022-G8-VC2-PART2#20]
Dear teacher @him-hey here is our mockup for sprint 1
![Image](https://user-images.githubusercontent.com/92006494/189529032-646df98d-1378-4e2e-947e-cf0977a96ed6.png)
![Image](https://user-images.githubusercontent.com/92006494/189529030-946638f1-200d-4c2c-9792-7d5d916ed66d.png)
![Image](https://user-images.githubusercontent.com/92006494/189529034-f450db2a-88c2-4d76-9d78-29ce0065621e.png)

![Image](https://user-images.githubusercontent.com/92006494/189566870-2fbf2cf0-20c9-417b-a0a5-3b55df47be31.png)
![Image](https://user-images.githubusercontent.com/92006494/189566871-7b3e72ce-a240-45bd-ab22-99ff992338d2.png)

**Comment by him-hey** [comment]
@sophalS I don't like the student detail view can you update it?

**Comment by sophalS** [comment]
Okay, I will update.
